services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - "./otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro"
    restart: unless-stopped
