version = 0.1

[default.global.parameters]
stack_name = "tracedeck-admin-frontend"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "tracedeck-admin-frontend"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
parameter_overrides = "DataBucketName=\"tracedeck-agent-family-varadha-996335889295-ap-south-1\" DataPrefix=\"\" CacheTTLSeconds=\"300\" LocalBackendURL=\"http://127.0.0.1:18080\""
