package constants

const (
	ConfigFieldTenantID               = "tenant_id"
	ConfigFieldDeviceID               = "device_id"
	ConfigFieldProfile                = "profile"
	ConfigFieldTransparencyMode       = "collection.transparency_mode"
	ConfigFieldBrowserURLMode         = "collection.browser.url_mode"
	ConfigFieldYouTubeClassification  = "collection.browser.youtube_classification"
	ConfigFieldYouTubeVideoIDMode     = "collection.browser.youtube_video_id_mode"
	ConfigFieldMediaPathMode          = "collection.media.path_mode"
	ConfigFieldLocalTTLDays           = "retention.local_ttl_days"
	ConfigFieldMaxLocalStorageMB      = "retention.max_local_storage_mb"
	ConfigFieldArchiveProvider        = "archive.provider"
	ConfigFieldArchiveBucket          = "archive.bucket"
	ConfigFieldArchivePrefixTemplate  = "archive.prefix_template"
	ConfigFieldArchiveUploadInterval  = "archive.upload_interval"
	ConfigFieldArchiveStandardIAUntil = "archive.storage_class_days.standard_ia_until"
	ConfigFieldArchiveAfter           = "archive.storage_class_days.archive_after"
	ConfigFieldEmailProvider          = "alerts.email.provider"
	ConfigFieldEmailTo                = "alerts.email.to"
	ConfigFieldEmailMinSeverity       = "alerts.email.min_severity"
	ConfigFieldEmailCooldownMinutes   = "alerts.email.cooldown_minutes"
	ConfigFieldAlertRules             = "alert_rules"
	ConfigFieldAlertRuleSeverity      = "alert_rules.*.severity"
	ConfigFieldAlertRuleThreshold     = "alert_rules.*.threshold_minutes_per_day"
	ConfigFieldMaxVideoMinutes        = "thresholds.max_video_minutes_per_day"
	ConfigFieldMaxSocialMinutes       = "thresholds.max_social_minutes_per_day"
	ConfigFieldMaxUnknownAppMinutes   = "thresholds.max_unknown_app_minutes_per_day"
	ConfigFieldLateNightUsageStart    = "thresholds.late_night_usage_start"
	ConfigFieldLateNightUsageEnd      = "thresholds.late_night_usage_end"
)

const (
	ConfigErrorMustNotBeEmpty              = "must not be empty"
	ConfigErrorMustBeGreaterThanZero       = "must be greater than zero"
	ConfigErrorMustNotBeNegative           = "must not be negative"
	ConfigErrorUnsupportedValueFormat      = "unsupported value %q"
	ConfigErrorSensitiveCapabilityDenyOnly = "is deny-only and must be set to deny"
	ConfigErrorArchiveProviderRequired     = "must not be none when archive is enabled"
	ConfigErrorEmailProviderRequired       = "must not be none when alerts are enabled"
	ConfigErrorEmailRecipientRequired      = "must include at least one recipient when alerts are enabled"
	ConfigErrorStandardIAAfterStandard     = "must be greater than standard days"
	ConfigErrorArchiveAfterStandardIA      = "must be greater than or equal to standard_ia_until"
	ConfigErrorRuleNameRequired            = "rule name must not be empty"
	ConfigErrorTimeMustUseHourMinute       = "must use HH:MM 24-hour format"
	ConfigErrorDurationRequired            = "must be a valid Go duration such as 10m or 1h"
)
