package constants

const (
	ConfigFieldTenantID               = "tenant_id"
	ConfigFieldDeviceID               = "device_id"
	ConfigFieldProfile                = "profile"
	ConfigFieldTransparencyMode       = "collection.transparency_mode"
	ConfigFieldBrowserURLMode         = "collection.browser.url_mode"
	ConfigFieldYouTubeClassification  = "collection.browser.youtube_classification"
	ConfigFieldYouTubeVideoIDMode     = "collection.browser.youtube_video_id_mode"
	ConfigFieldForegroundWindowTitle  = "collection.foreground_app.window_title_mode"
	ConfigFieldSoftwareInventoryMode  = "collection.software.inventory_mode"
	ConfigFieldMediaPathMode          = "collection.media.path_mode"
	ConfigFieldLocalTTLDays           = "retention.local_ttl_days"
	ConfigFieldMaxLocalStorageMB      = "retention.max_local_storage_mb"
	ConfigFieldArchiveProvider        = "archive.provider"
	ConfigFieldArchiveBucket          = "archive.bucket"
	ConfigFieldArchivePrefixTemplate  = "archive.prefix_template"
	ConfigFieldArchiveUploadInterval  = "archive.upload_interval"
	ConfigFieldArchiveStandardIAUntil = "archive.storage_class_days.standard_ia_until"
	ConfigFieldArchiveAfter           = "archive.storage_class_days.archive_after"
	ConfigFieldBackendSyncBaseURL     = "backend_sync.base_url"
	ConfigFieldBackendSyncBatchLimit  = "backend_sync.batch_limit"
	ConfigFieldBackendSyncTimeout     = "backend_sync.request_timeout"
	ConfigFieldOpenTelemetryProtocol  = "observability.opentelemetry.protocol"
	ConfigFieldOpenTelemetryEndpoint  = "observability.opentelemetry.endpoint"
	ConfigFieldOpenTelemetryBatch     = "observability.opentelemetry.batch_limit"
	ConfigFieldOpenTelemetryTimeout   = "observability.opentelemetry.request_timeout"
	ConfigFieldOpenTelemetryAttempts  = "observability.opentelemetry.retry.max_attempts"
	ConfigFieldEmailProvider          = "alerts.email.provider"
	ConfigFieldEmailFrom              = "alerts.email.from"
	ConfigFieldEmailTo                = "alerts.email.to"
	ConfigFieldEmailMinSeverity       = "alerts.email.min_severity"
	ConfigFieldEmailCooldownMinutes   = "alerts.email.cooldown_minutes"
	ConfigFieldPushProvider           = "alerts.push.provider"
	ConfigFieldPushSubscriptionFile   = "alerts.push.subscription_file"
	ConfigFieldPushVAPIDPublicKey     = "alerts.push.vapid_public_key"
	ConfigFieldPushVAPIDPrivateKey    = "alerts.push.vapid_private_key_file"
	ConfigFieldPushVAPIDSubject       = "alerts.push.vapid_subject"
	ConfigFieldPushTTLSeconds         = "alerts.push.ttl_seconds"
	ConfigFieldPushMinSeverity        = "alerts.push.min_severity"
	ConfigFieldPushCooldownMinutes    = "alerts.push.cooldown_minutes"
	ConfigFieldAlertRules             = "alert_rules"
	ConfigFieldAlertRuleSeverity      = "alert_rules.*.severity"
	ConfigFieldAlertRuleThreshold     = "alert_rules.*.threshold_minutes_per_day"
	ConfigFieldMaxVideoMinutes        = "thresholds.max_video_minutes_per_day"
	ConfigFieldMaxSocialMinutes       = "thresholds.max_social_minutes_per_day"
	ConfigFieldMaxUnknownAppMinutes   = "thresholds.max_unknown_app_minutes_per_day"
	ConfigFieldLateNightUsageStart    = "thresholds.late_night_usage_start"
	ConfigFieldLateNightUsageEnd      = "thresholds.late_night_usage_end"
)

const (
	ConfigErrorMustNotBeEmpty              = "must not be empty"
	ConfigErrorMustBeGreaterThanZero       = "must be greater than zero"
	ConfigErrorMustNotBeNegative           = "must not be negative"
	ConfigErrorUnsupportedValueFormat      = "unsupported value %q"
	ConfigErrorSensitiveCapabilityDenyOnly = "is deny-only and must be set to deny"
	ConfigErrorArchiveProviderRequired     = "must not be none when archive is enabled"
	ConfigErrorEmailProviderRequired       = "must not be none when alerts are enabled"
	ConfigErrorEmailSenderRequired         = "must include a sender when alerts are enabled"
	ConfigErrorEmailRecipientRequired      = "must include at least one recipient when alerts are enabled"
	ConfigErrorAlertProviderRequired       = "must enable at least one alert provider when alerts are enabled"
	ConfigErrorPushSubscriptionRequired    = "must include a subscription file when web push is enabled"
	ConfigErrorPushPublicKeyRequired       = "must include a VAPID public key when web push is enabled"
	ConfigErrorPushPrivateKeyRequired      = "must include a VAPID private key file when web push is enabled"
	ConfigErrorPushSubjectRequired         = "must include a VAPID subject when web push is enabled"
	ConfigErrorStandardIAAfterStandard     = "must be greater than standard days"
	ConfigErrorArchiveAfterStandardIA      = "must be greater than or equal to standard_ia_until"
	ConfigErrorRuleNameRequired            = "rule name must not be empty"
	ConfigErrorTimeMustUseHourMinute       = "must use HH:MM 24-hour format"
	ConfigErrorDurationRequired            = "must be a valid Go duration such as 10m or 1h"
	ConfigErrorURLRequired                 = "must be a valid http or https URL"
)
